version: "3.3" 
services:
  mysql:
    image: mysql:5.7
    container_name: mysql5.7_dev
    volumes:
      - ./backup:/backup
      - ./db_data:/var/lib/mysql
    ports:
      - '50002:3306'
    env_file:
      - database.env
